// frontend/frontend_vue/src/components/AuthGuard.vue
<template>
  <div>
    <!-- Loading State -->
    <div v-if="authStore.isLoading" class="flex items-center justify-center min-h-[400px]">
      <div class="text-gray-600">Loading...</div>
    </div>

    <!-- For public routes or authenticated users, show content normally -->
    <div v-else-if="isPublicRoute || authStore.isAuthenticated">
      <slot />
    </div>

    <!-- For protected routes when unauthenticated, show login requirement -->
    <div v-else-if="isProtectedRoute && !authStore.isAuthenticated" class="flex flex-col items-center justify-center min-h-[500px] p-8">
      <div class="max-w-md text-center space-y-6">
        <div class="text-6xl mb-4">🔒</div>
        <h1 class="text-2xl font-bold text-gray-800 mb-2">
          {{ getPageTitle() }} - Login Required
        </h1>
        <p class="text-gray-600 mb-6">
          You need to sign in to access the {{ getPageTitle().toLowerCase() }} page.
        </p>
        <div class="space-y-4">
          <AuthButton :compact="false" />
          <p class="text-sm text-gray-500">
            Sign in to start using our CZSU Multi-agent Text-to-SQL System
          </p>
        </div>
      </div>
    </div>

    <!-- For any other unauthenticated routes, redirect to login -->
    <div v-else class="flex items-center justify-center min-h-[400px]">
      <div class="text-gray-600">Redirecting to login...</div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useRoute } from 'vue-router';
import { useAuthStore } from '@/stores/auth';
import AuthButton from '@/components/AuthButton.vue';

// Public routes that don't require authentication
const PUBLIC_ROUTES = ["/", "/contacts", "/login"];

// Routes that should allow navigation but protect content behind login
const PROTECTED_ROUTES = ["/chat", "/catalog", "/data"];

// Composables
const route = useRoute();
const authStore = useAuthStore();

// Computed
const isPublicRoute = computed(() => PUBLIC_ROUTES.includes(route.path));
const isProtectedRoute = computed(() => PROTECTED_ROUTES.includes(route.path));

// Methods
const getPageTitle = (): string => {
  switch (route.path) {
    case "/chat":
      return "Chat";
    case "/catalog":
      return "Catalog";
    case "/data":
      return "Data";
    default:
      return "This Page";
  }
};
</script>

// frontend/src/components/AuthGuard.tsx
"use client";
import { useSession } from "next-auth/react";
import { useRouter, usePathname } from "next/navigation";
import { useEffect } from "react";
import AuthButton from "./AuthButton";

// Public routes that don't require authentication
const PUBLIC_ROUTES = ["/", "/contacts", "/login"];

// Routes that should allow navigation but protect content behind login
const PROTECTED_ROUTES = ["/chat", "/catalog", "/data"];

export default function AuthGuard({ children }: { children: React.ReactNode }) {
  const { status } = useSession();
  const pathname = usePathname();

  const isPublicRoute = PUBLIC_ROUTES.includes(pathname);
  const isProtectedRoute = PROTECTED_ROUTES.includes(pathname);

  if (status === "loading") {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="text-gray-600">Loading...</div>
      </div>
    );
  }

  // For public routes or authenticated users, show content normally
  if (isPublicRoute || status === "authenticated") {
    return <>{children}</>;
  }

  // For protected routes when unauthenticated, show login requirement
  if (isProtectedRoute && status === "unauthenticated") {
    const getPageTitle = () => {
      switch (pathname) {
        case "/chat":
          return "Chat";
        case "/catalog":
          return "Catalog";
        case "/data":
          return "Data";
        default:
          return "This Page";
      }
    };

    return (
      <div className="flex flex-col items-center justify-center min-h-[500px] p-8">
        <div className="max-w-md text-center space-y-6">
          <div className="text-6xl mb-4">🔒</div>
          <h1 className="text-2xl font-bold text-gray-800 mb-2">
            {getPageTitle()} - Login Required
          </h1>
          <p className="text-gray-600 mb-6">
            You need to sign in to access the {getPageTitle().toLowerCase()} page.
          </p>
          <div className="space-y-4">
            <AuthButton compact={false} />
            <p className="text-sm text-gray-500">
              Sign in to start using our CZSU Multi-agent Text-to-SQL System
            </p>
          </div>
        </div>
      </div>
    );
  }

  // For any other unauthenticated routes, redirect to login
  return (
    <div className="flex items-center justify-center min-h-[400px]">
      <div className="text-gray-600">Redirecting to login...</div>
    </div>
  );
}
