// frontend/src/app/catalog/page.tsx
"use client";
import CatalogTable from '../../components/DatasetsTable';
import { useRouter } from 'next/navigation';

export default function CatalogPage() {
  const router = useRouter();
  const handleCatalogRowClick = (selection_code: string) => {
    router.push(`/data?table=${encodeURIComponent(selection_code)}`);
  };
  return (
    <div className="unified-white-block-system">
      <div className="table-container">
        <CatalogTable onRowClick={handleCatalogRowClick} />
      </div>
    </div>
  );
}

// frontend/frontend_vue/src/views/Catalog.vue
<template>
  <div class="unified-white-block-system">
    <div class="table-container">
      <DatasetsTable :on-row-click="handleCatalogRowClick" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router'
import DatasetsTable from '@/components/DatasetsTable.vue'

const router = useRouter()

const handleCatalogRowClick = (selection_code: string) => {
  router.push(`/data?table=${encodeURIComponent(selection_code)}`)
}
</script>
